INSERT INTO EXCHANGE_VALUE (ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MULTIPLE)
VALUES (10001, 'USD', 'INR', 65);
INSERT INTO EXCHANGE_VALUE (ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MULTIPLE)
VALUES (10002, 'EUR', 'INR', 75);
INSERT INTO EXCHANGE_VALUE (ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MULTIPLE)
VALUES (10003, 'AUD', 'INR', 25);